[package]
name = "sysadmin-dao"
version = "0.1.0"
authors = ["imac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version= "0.3.4", features = ["mysql"] }
