[package]
name = "sysadmin-config"
version = "0.1.0"
authors = ["imac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = "0.10.1"
serde = { version = "1.0.106" ,features = ["derive"] }