[package]
name = "sysadmin-middleware"
version = "0.1.0"
authors = ["imac"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-service = "1.0.5"
futures = "0.3.5"
actix-web = "2.0.0"